#!/bin/sh

AcctName="itadmin"
AcctPWD="G%8KzYn5"

outputTest=$(dscl . authonly $AcctName $AcctPWD)

if [ "$outputTest" = "" ]; then
    echo "<result>Correct Password</result>"
else
    echo "<result>Needs to be changed by Administrator</result>"
fi
