#!/bin/bash
#This Script leverages SPAWN to input the necessary credentials, authenticate with elevated privileges (SUDO), and update the managed password.

# Define variables
admin_user="itadmin"
admin_password="G%8Kz"
target_user="Admin"
new_password="%0vA!F9g"


expect <<EOF
spawn su - $admin_user
expect "Password:"
send "$admin_password\r"
expect "# "
send "sudo passwd $target_user\r"
expect "(current) UNIX password:"
send "$admin_password\r"
expect "New password:"
send "$new_password\r"
expect "Retype new password:"
send "$new_password\r"
expect "# "
send "exit\r"
expect eof
EOF

if [ $? -eq 0 ]; then
    echo "Password for user $target_user changed successfully."
else
    echo "Failed to change the password for user $target_user."
fi
